name: Test2
on: push

jobs:
  tests2:
    strategy:
      matrix:
        version: [12.x, 14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - run: yarn test --json --outputFile=result.json --testLocationInResults
      - uses: ./
        if: always()
        with:
          action-name: jest report (${{ matrix.version }})
          github-token: ${{ secrets.GITHUB_TOKEN }}
